/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Generates a CAPTCHA asynchronously with retry logic.
 *
 * 异步生成验证码，包含重试逻辑。
 */
export declare function captcha(w: number, h: number, num: number): Promise<[Uint8Array, Array<string>, Array<number[]>]>
