/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Generates a CAPTCHA asynchronously.
 *
 * 异步生成验证码。
 */
export declare function captcha(w: number, h: number, num: number): Promise<[Buffer, Array<string>, Array<number[]>]>
